name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: |
          docker build -t rungroups:latest .

      - name: Deploy html
        run: |
          docker run \
          -e CLOUDFLARE_API_TOKEN=${{ env.CLOUDFLARE_API_TOKEN }} \
          rungroups:latest bb deploy
